language:
 - python
 - java

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

jdk:
  - oraclejdk6
  - oraclejdk7
  - oraclejdk8

script:
 - python printVersion.py
 - javac testing.java
 - java testing
